name: PR Auto-build

on:
  pull_request_review:
    types: [submitted]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger pr-autobuild action for building PR
        uses: nikhilaii93/pr-autobuild@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          DEFAULT_APPROVAL_COUNT_ENV: 0
          GITHUB_NAME: epicarts
          BUILD_COMMENT_ENV: "OK to test"
          DEFAULT_MERGE_ENV: merge
