name: Merge Pal (events)

on:
  pull_request_review: # try to merge after review

jobs:
  # thats's all. single step is needed - if PR is mergeable according to
  # branch protection rules it will be merged automatically
  mergepal:
    # 리뷰 상태가 appreved 승인 됨. 일 경우
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: maxkomarychev/merge-pal-action@v0.5.1
        with:
          token: ${{ secrets.TOKEN }}
