name: pr_approve

#master 브런치의 PR 리뷰가 달렸을 때.
on:
  pull_request_review_comment:
    branches:
      - master

jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hellossssssssasdasd ${{ github.event.inputs.name }}"
    - name: Merge pull requests
      uses: pascalgn/automerge-action@v0.9.0
