name: pr_approve

#master 브런치의 PR 리뷰가 달렸을 때.
on:
  pull_request_review:
    branches: [ master ]
    types: [submitted]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger pr-autobuild action for building PR
        uses: nikhilaii93/pr-autobuild@master
        env:
          GITHUB_TOKEN: ${{ secrets.bot_token }}
          DEFAULT_APPROVAL_COUNT_ENV: 0
          BUILD_COMMENT_ENV: "OK!!"
  greet:
    runs-on: ubuntu-latest

    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello pr_approve ${{ github.event.inputs.name }}"
