name: pr_approve

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request_review:
    branches: [ master ]
    types: [submitted]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger pr-autobuild action for building PR
        uses: nikhilaii93/pr-autobuild@master
        env:
          GITHUB_TOKEN: ${{ secrets.bot_token }}
          DEFAULT_APPROVAL_COUNT_ENV: 0
          BUILD_COMMENT_ENV: "OK!!"
